### PR TITLE
end the campaign properly when a mission is skipped

### LINKED ISSUE #4412: Skipping training causes crash in FSPort
If the last mission in a campaign is a training mission, attempting to skip that mission using "skip training" will cause a crash.  This occurs on FSPort because the last mission is configured as a training mission.

Reported by Daft Mugi on Discord.

### PR DESCRIPTION
**Pull request by Goober5000**
The "skip training" button and the "exit loop" button should both check whether the campaign is actually over before attempting to load the next mission.  The fix is simple - just use the same logic as in `mission_campaign_skip_to_next`.

Fixes #4412.

### CODE REVIEW

File: code/mission/missioncampaign.cpp [hunk 1]
```diff
@@ -1822,7 +1822,12 @@ void mission_campaign_exit_loop()
 
 	// set things up for next mission
 	mission_campaign_next_mission();
```
Comment (jg18) [inline code/mission/missioncampaign.cpp:1824]: Is this call still correctly placed?

**Review by jg18 — APPROVED** [review]
Looks good. Just one question.

File: code/mission/missioncampaign.cpp (hunk 1 above)
Comment (Goober5000) [reply code/mission/missioncampaign.cpp:1824]: It should be.  In any case, there's no harm in calling it even if the campaign has ended.
