### PR TITLE
Fix False Null MOI warnings

### LINKED ISSUE #4534: False Null MOI warnings
The first 22.3 nightly gives these warnings where 22.2.0 does not. Does not apply to all models. I don't see a pattern to what models trigger it. Triton in FSU is a perfect example. Also happens with the Fenris. I have verified the POFs in question absolutely do have MOI data.

Load up 22.2.0 debug with FSU 4.6.6. Go to the lab and view the Triton. No warning.
Load up 22.3 debug with FSU 4.6.6. Go to the lab and view the Triton. Null MOI warning is triggered.

### PR DESCRIPTION
**Pull request by wookieejedi**
In #4443, `fl_near_zero` was set to use default epsilon values in the `IS_VEC_NULL` check. In this comparison, epsilon is the wrong threshold because it used to have a much smaller threshold. The fix restores the previous definitions of `IS_VEC_NULL` and `IS_VEC_NULL_SQ_SAFE` by exposing the epsilon value as an optional parameter (similar to how `IS_NEAR_ZERO` used to work. This PR also restores `IS_VEC_NULL_SQ_SAFE` where it was replaced by `IS_VEC_NULL.`

Fixes #4534.

### CODE REVIEW

File: code/math/vecmat.h [hunk 1]
```diff
@@ -22,9 +22,15 @@
 //Macros/functions to fill in fields of structures
 
 //macro to check if vector is zero
```
Comment (JohnAFernandez) [inline code/math/vecmat.h:24]: Can you change this comment to match what `IS_VEC_NULL_SQ_SAFE` is specifically for, and then probably move this comment to be above `IS_VEC_NULL`?

**Review by JohnAFernandez — CHANGES_REQUESTED** [review]

File: code/math/vecmat.h (hunk 1 above)
Comment (wookieejedi) [reply code/math/vecmat.h:24]: Sure, the original code had it this way but happy to take the opportunity to update comments.

Comment (Goober5000) [reply code/math/vecmat.h]: The original macro split happened back in 2009: 75a514b5f9

I would be curious if anyone has a good idea how these thresholds should be determined.  The well-known `epsilon` is for addition and subtraction; I would assume there is some other standard for multiplication and squaring.

Comment (JohnAFernandez) [reply code/math/vecmat.h]: My theory is that the `SQ_SAFE` version ensures that squaring a float is safe. But I don't have evidence for that beyond common sense.

Comment (Baezon) [reply code/math/vecmat.h]: I think the existing epsilon is fine. This issue is MOI-specific, imo. Due to the way they are calculated and used, they are unfortunately extremely small numbers a lot of the time.

Comment (wookieejedi) [reply code/math/vecmat.h]: Makes sense. Are folks good with the current version then?

**Review by JohnAFernandez — APPROVED** [review]

File: code/math/vecmat.h (hunk 1 above)
Comment (JohnAFernandez) [reply code/math/vecmat.h]: Yeah, go ahead

File: code/math/floating.h [hunk 2]
```diff
@@ -97,10 +97,9 @@ float fl_isqrt( float x )
 */
 
 // sees if a floating point number is within the minimum tolerance of zero
-inline bool fl_near_zero(float a)
+inline bool fl_near_zero(float a, float e = std::numeric_limits<float>::epsilon())
```
Comment (Goober5000) [inline code/math/floating.h:100]: Since this is adding a new parameter, change the comment to be this:
```
// sees if a floating point number is within a certain threshold (by default, epsilon) of zero
```

File: code/math/vecmat.h [hunk 3]
```diff
@@ -21,10 +21,17 @@
 
 //Macros/functions to fill in fields of structures
 
-//macro to check if vector is zero
-#define IS_VEC_NULL(v) (fl_near_zero((v)->xyz.x) && \
-						fl_near_zero((v)->xyz.y) && \
-						fl_near_zero((v)->xyz.z))
+//macro to check if vector is zero, uses 1e-16 as a minimum tolerance
```
Comment (Goober5000) [inline code/math/vecmat.h:24]: Change the comment to something like this:
```
// macro to check if vector is close to zero or would be close to zero after squaring
```
And change the next comment to something like this:
```
// macro to check if vector is close to zero
```

**Review by Goober5000 — CHANGES_REQUESTED** [review]

File: code/math/vecmat.h (hunk 3 above)
Comment (Goober5000) [reply code/math/vecmat.h:24]: Also add the hash of the commit that originally split the macros into two.

File: code/math/floating.h (hunk 2 above)
Comment (wookieejedi) [reply code/math/floating.h:100]: Good idea, just added.

File: code/math/vecmat.h (hunk 3 above)
Comment (wookieejedi) [reply code/math/vecmat.h]: Thanks, just updated.

**Review by Goober5000 — APPROVED** [review]

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Actually hang on while I research some floating point things

**Review by Goober5000 — APPROVED** [review]

**Comment by Goober5000** [comment]
Approving this for the time being.  Other floating-point changes can go in a follow-up PR.
