### PR TITLE
Fix max Z speed when using ETS and engine damage tracking

### LINKED ISSUE #5367: Bug with waypoint speed following and damaged engines
```
DefCynodont — Yesterday at 10:39 PM
I have just confirmed, in the MVPs, at 48% engine integrity, a Faustus will become "effectively disabled". 
it looks like the moment the engine hitpoints are supposed to trigger the max-speed reduction, it just reduces the max speed to zero
```

[https://discord.com/channels/223511295431933953/223511391531827200/1099525030469181471](url)

Confirmed that #5292 causes this. 

Test mission:
[EngineHealthSpeedTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/11302827/EngineHealthSpeedTest.zip)

### PR DESCRIPTION
**Pull request by wookieejedi**
Follow up for #5137 and #5292. This engine strength check thus needs to be added to all instances where `max_vel.xyz.z` is updated, so a function was created and added in respective locations. Fixes #5367.

### CODE REVIEW

File: code/hud/hudets.cpp [hunk 1]
```diff
@@ -174,6 +159,34 @@ float ets_get_max_speed(object* objp, float engine_energy)
 	}
 }
 
+void update_max_speed(object* ship_objp)
+{
+	// get max possible speed then adjust and set based on engine health
```
Comment (JohnAFernandez) [inline code/hud/hudets.cpp:164]: Need some asserts and early returns so that if someone calls this function incorrectly in the future, we won't be left with a mystery ctd.

**Review by JohnAFernandez — CHANGES_REQUESTED** [review]

File: code/hud/hudets.cpp (hunk 1 above)
Comment (wookieejedi) [reply code/hud/hudets.cpp:167]: Thanks for kicking off the review. The `ets_get_max_speed` function above uses these checks, so I used that format in this new push.

Comment (JohnAFernandez) [reply code/hud/hudets.cpp:167]: I mean that's all I saw.  It's not a large pr, and it makes sense.  Standardizing how a value is set should logocally fix the issue and prevent future bugs as well.

**Review by JohnAFernandez — APPROVED** [review]

File: code/ship/shiphit.cpp [hunk 2]
```diff
@@ -2409,6 +2410,8 @@ static void ship_do_damage(object *ship_objp, object *other_obj, vec3d *hitpos,
 		// apply damage to subsystems, and get back any remaining damage that needs to go to the hull
 		damage = do_subobj_hit_stuff(ship_objp, other_obj, hitpos, submodel_num, damage, &apply_hull_armor);
 
+		ets_update_max_speed(ship_objp);
+
```
Comment (Baezon) [inline code/ship/shiphit.cpp:2414]: I would be as specific as possible and check directly for an engine subsystem being damaged to under the threshold inside the function. The case where we *know for certain* the max speed *will* change, not just whenever the ship takes damage.

The idea is to allow scripts to mess with velocity as much as possible, and only override it when we absolutely must.

**Review by Baezon — CHANGES_REQUESTED** [review]

File: code/hud/hudets.cpp [hunk 3]
```diff
@@ -117,6 +118,31 @@ void update_ets(object* objp, float fl_frametime)
...
+	//						2. if strength < 0.5 then max_speed = sqrt(strength)
+	//
+	//					 This will translate to 71% max speed at 50% engines, and 31% max speed at 10% engines
+	//
+
+	float eng_current_strength = ship_get_subsystem_strength(ship_p, SUBSYSTEM_ENGINE);
+
+	// only update max speed if aggregate engine health has changed
+	// which helps minimze amount of overrides to max speed
+	if (eng_current_strength != ship_p->prev_engine_aggregate_hits) {
```
Comment (Baezon) [inline code/hud/hudets.cpp:133]: Minor, but since we're going to compare this to `strength` it should probably be named as such instead of `..._hits` since we aren't using direct hp values.

File: code/hud/hudets.cpp [hunk 4]
```diff
@@ -117,6 +118,31 @@ void update_ets(object* objp, float fl_frametime)
 		}
 	}
 
+	// update max speed, moved from 'update_ets' function as part of max speed cleanup -Asteroth and wookieejedi
```
Comment (Baezon) [inline code/hud/hudets.cpp:121]:
```suggestion
```

**Review by Baezon — CHANGES_REQUESTED** [review]

File: code/hud/hudets.cpp (hunk 3 above)
Comment (wookieejedi) [reply code/hud/hudets.cpp]: Good point, just updated

**Review by Baezon — APPROVED** [review]
