### PR TITLE
remove incorrect setting of ship status

### LINKED ISSUE #5661: RC8 and later: Ai wingmen refuse any order at all times
Steps to reproduce:

1. Play a mission where you can order your wingmen
2. target a wingman - note how it has the "no orders" indicator - regardless of whatever order they were given in FRED.
3. order your wingman to guard you
4. notice how very briefly, "guard alpha 1" flashes before the craft resets to "no orders".

### PR DESCRIPTION
**Pull request by Goober5000**
There is a bit of code in missionparse that sets the parse object because in-game joining needs it.  This is unrelated to ship status, so the status shouldn't be changed.  This fixes the bug and adds a comment to clarify the situation, as well as some warnings to help track down incorrect joining states.

Fixes #5661.  Follow-up to #5658 (where the regression was introduced) and #4836 (which fixed in-game joining).

Also adds a ship registry entry for support ships, since in testing that issue was (correctly) flagged by the warnings.

### CODE REVIEW

File: code/mission/missionparse.cpp [hunk 1]
```diff
@@ -2514,11 +2514,21 @@ int parse_create_object_sub(p_object *p_objp, bool standalone_ship)
...
+
+		if (entry->status == ShipStatus::INVALID) {
+			Warning(LOCATION, "Potential in-game join bug: ship registry status for %s is INVALID", shipp->ship_name);
+		}
+		if (entry->p_objp == nullptr) {
+			Warning(LOCATION, "Potential in-game join bug: ship registry parse object for %s is nullptr", shipp->ship_name);
+		} else if (entry->p_objp != p_objp) {
+			Warning(LOCATION, "Potential in-game join bug: ship registry parse object for %s is different from its expected value", shipp->ship_name);
+		}
+
```
Comment (notimaginative) [inline code/mission/missionparse.cpp:2531]: Would these do better under a multi check, or perhaps tweak the message a bit? The message text seems specific to multi but since you hit it in single player too I wonder if it might be confusing if hit in other non-multi circumstances.

Comment (Goober5000) [reply code/mission/missionparse.cpp:2531]: Ideally it shouldn't be hit in single player from now on, but yeah that's a good point.  I'll edit them.

**Review by notimaginative — APPROVED** [review]
