### PR TITLE
fix model_update_instance to handle LODs

### LINKED ISSUE #3063: Not rotating parts at greater distance from model
MediaVPS
When you look at Shivan Com Node 1 in "Into the Lion's Den", you'll notice rotating parts. But SC2 and SC3 are static. When player flies towards SC2 or SC3, at some distance submodels starts rotating. Before commit below everything was ok.
```
88c1d8a02a9062c394262aca3888e2debb15c22a is the first bad commit
commit 88c1d8a02a9062c394262aca3888e2debb15c22a
Author: Goober5000 <ipw47@mailbox.org>
Date:   Sat Dec 12 02:04:02 2020 -0500

    consolidate model instance code

 code/ai/aibig.cpp                     |   3 +-
 code/ai/aicode.cpp                    |   5 +-
 code/ai/aiturret.cpp                  |  13 +-
 code/decals/decals.cpp                |  11 +-
 code/hud/hudtarget.cpp                |   1 -
 code/menuui/techmenu.cpp              |  21 +-
 code/mission/missionparse.cpp         |   2 +-
 code/missionui/redalert.cpp           |   2 +-
 code/model/model.h                    |  53 ++---
 code/model/modelanim.cpp              |  54 ++---
 code/model/modelcollide.cpp           |  13 +-
 code/model/modelread.cpp              | 381 ++++++++++++----------------------
 code/model/modelrender.cpp            |  35 +---
 code/network/multi_obj.cpp            |  24 ++-
 code/network/multimsgs.cpp            |  16 +-
 code/object/collideshipship.cpp       |  10 +-
 code/parse/sexp.cpp                   |  40 ++--
 code/scripting/api/objs/subsystem.cpp |  10 +-
 code/ship/ship.cpp                    |  61 +++---
 code/ship/ship.h                      |   4 +-
 code/ship/shipfx.cpp                  |  31 +--
 code/ship/shiphit.cpp                 |   6 +-
 22 files changed, 352 insertions(+), 444 deletions(-)
```

### PR DESCRIPTION
**Pull request by Goober5000**
Add back the copying of model instance information to submodels in other LODs.  This was inadvertently removed in commit 88c1d8a02a9062c394262aca3888e2debb15c22a.

This fixes #3063.

### CODE REVIEW

File: code/model/modelread.cpp [hunk 1]
```diff
@@ -4476,16 +4476,19 @@ void model_update_instance(int model_instance_num, int submodel_num, flagset<Shi
...
 	auto pmi = model_get_instance(model_instance_num);
 	auto pm = model_get(pmi->model_num);
-	model_update_instance(pm, pmi, submodel_num, flags);
+	model_update_instance(pm, pmi, nullptr, submodel_num, flags);
 }
 
-void model_update_instance(polymodel *pm, polymodel_instance *pmi, int submodel_num, flagset<Ship::Subsystem_Flags>& flags)
+/*
+ * This function handles copying submodel instance information to other submodel instances as appropriate.  All callers should pass nullptr for the
+ * copy_from parameter.  This parameter is used for copying data to other LODs, and is only specified from within model_update_instance itself.
```
Comment (asarium) [inline code/model/modelread.cpp:4484]: If the parameter is purely internal then maybe it would be better to just have a local function here that has the parameter and a "public" one where the parameter is not present?

**Review by asarium — APPROVED** [review]

File: code/model/modelread.cpp (hunk 1 above)
Comment (Goober5000) [reply code/model/modelread.cpp:4484]: I guess that would make sense.
