### PR TITLE
remove Object.parent_type

### LINKED ISSUE #4105: Read access violation in ship_maybe_praise_self
```Unhandled exception thrown: read access violation.
**killer_sp** was 0xFFFFF7F58B773480.
```

This happened at minute 40 of a benchmark mayhem run after benchmarking the same mayhem for hours before and not hitting it, so it's a pretty rare thing.

```
fs2_open_21_5_0_x64_AVX2.exe!ship_maybe_praise_self(ship * deader_sp, ship * killer_sp) Line 16166	C++
fs2_open_21_5_0_x64_AVX2.exe!ship_hit_kill(object * ship_objp, object * other_obj, vec3d * hitpos, float percent_killed, bool self_destruct, bool always_log_other_obj) Line 1942	C++
fs2_open_21_5_0_x64_AVX2.exe!ship_do_damage(object * ship_objp, object * other_obj, vec3d * hitpos, float damage, int quadrant, int submodel_num, int damage_type_idx, bool wash_damage) Line 2555	C++
fs2_open_21_5_0_x64_AVX2.exe!ship_apply_local_damage(object * ship_objp, object * other_obj, vec3d * hitpos, float damage, int damage_type_idx, int quadrant, bool create_spark, int submodel_num, vec3d * hit_normal) Line 2821	C++
fs2_open_21_5_0_x64_AVX2.exe!collide_ship_ship(obj_pair * pair) Line 1383	C++
fs2_open_21_5_0_x64_AVX2.exe!`anonymous namespace'::obj_collide_pair(object * A, object * B) Line 948	C++
fs2_open_21_5_0_x64_AVX2.exe!`anonymous namespace'::obj_find_overlap_colliders(std::vector<int,std::allocator<int>> & overlap_list_out, std::vector<int,std::allocator<int>> & list, int axis, bool collide) Line 987	C++
fs2_open_21_5_0_x64_AVX2.exe!obj_move_all(float frametime) Line 1601	C++
fs2_open_21_5_0_x64_AVX2.exe!game_simulation_frame() Line 3596	C++
fs2_open_21_5_0_x64_AVX2.exe!game_frame(bool paused) Line 4001	C++
fs2_open_21_5_0_x64_AVX2.exe!game_do_state(int state) Line 6240	C++
[Inline Frame] fs2_open_21_5_0_x64_AVX2.exe!gameseq_process_events() Line 389	C++
fs2_open_21_5_0_x64_AVX2.exe!game_main(int argc, char * * argv) Line 6613	C++
fs2_open_21_5_0_x64_AVX2.exe!SDL_main(int argc, char * * argv) Line 7701	C++
fs2_open_21_5_0_x64_AVX2.exe!main_getcmdline(...) Line 177	C
```

I didn't see an obvious way that this could happen and thus best way to guard against it, so I've archived the pdb and mdmp. It's over the github attach limit though so I'll reply with a link

### PR DESCRIPTION
**Pull request by Goober5000**
It's theoretically possible for `parent_type` to get out of sync with the parent's type, particularly if the parent is destroyed.  Since the field is almost never used, it can be removed.

Should fix #4105.

### CODE REVIEW

File: code/ship/shiphit.cpp [hunk 1]
```diff
@@ -1928,11 +1928,10 @@ void ship_hit_kill(object *ship_objp, object *other_obj, vec3d *hitpos, float pe
 		}
 
 		// maybe praise the player for this kill
-		if ( (killer_damage_percent > 10) && (other_obj != NULL) ) {
+		if ( (killer_damage_percent > 10) && (other_obj != nullptr) && (other_obj->parent >= 0) ) {
 			if (other_obj->parent_sig == Player_obj->signature) {
 				ship_maybe_praise_player(sp);
-			}
-			else if ((other_obj->parent_type == OBJ_SHIP) || (other_obj->parent_type == OBJ_START))  {
```
Comment (Goober5000) [inline code/ship/shiphit.cpp:1935]: I removed `OBJ_START` because this is the player object type, and players shouldn't be sending automatic messages.

**Review by wookieejedi — APPROVED** [review]
LGTM

**Review by JohnAFernandez — APPROVED** [review]
Looks pretty straightforward
