### PR TITLE
fix STAY_NEAR_TARGET_ITEM

### LINKED ISSUE #6475: "Stay Near Me" and "Stay Near My Target" comms menu items don't function properly
Issuing a "Stay Near Me" order either does nothing, or causes the recipient to fly in a tight circle. Issuing a "Stay Near My Target" order does nothing at all, and is only available for hostile ships for some reason.

Both issues can be observed in the released version of _Between the Ashes._ If you use a debug build and turn on the Mod Debugging option, a test mission will be available in the simulator.

### PR DESCRIPTION
**Pull request by Goober5000**
Fixes a few issues in the handling of the stay-near orders:

1. Allow "Stay near me" and "Stay near my target" to work even if the teams do not match
2. Allow "Stay near my target" to be issued regardless of team
3. Avoid divide-by-zero errors when running `ai_stay_near()`

Additionally, when issuing the stay-near-target order via hud squad message, default to a distance of 300, the same as the sexp.

Fixes #6475.

### CODE REVIEW

File: code/hud/hudsquadmsg.cpp [hunk 1]
```diff
@@ -147,8 +147,9 @@ SCP_vector<player_order> Player_orders = {
 };
 
 const SCP_set<size_t> default_messages{ ATTACK_TARGET_ITEM , DISABLE_TARGET_ITEM , DISARM_TARGET_ITEM , PROTECT_TARGET_ITEM , IGNORE_TARGET_ITEM , FORMATION_ITEM , COVER_ME_ITEM , ENGAGE_ENEMY_ITEM , DEPART_ITEM , DISABLE_SUBSYSTEM_ITEM };
+// note: STAY_NEAR_TARGET_ITEM appears in both enemy and friendly sets
 const SCP_set<size_t> enemy_target_messages{ ATTACK_TARGET_ITEM , DISABLE_TARGET_ITEM , DISARM_TARGET_ITEM , IGNORE_TARGET_ITEM , STAY_NEAR_TARGET_ITEM , CAPTURE_TARGET_ITEM , DISABLE_SUBSYSTEM_ITEM };
```
Comment (jg18) [inline code/hud/hudsquadmsg.cpp:151]: Why are we keeping `STAY_NEAR_TARGET_ITEM`  in `enemy_target_messages`?

Or did I miss something and this behavior now works for enemy tarets?

Comment (Goober5000) [reply code/hud/hudsquadmsg.cpp:151]: Because, conceptually, the order should be valid for both friendlies and enemies.  I could see potential uses for either one.  But to your point, yes, the behavior now works for both friendlies and enemies, and I've tested it with both.
