### PR TITLE
Fix wing persistence and ensure checks for depleted wings are valid

### LINKED ISSUE #4269: wing wave discrepancy in red_alert_bash_wingman_status
In `red_alert_bash_wingman_status`, in the section of code commented with `// if all parse objects in a wing have been removed, decrement the count for that wing`, there is contradictory logic.  The wing's `num_waves` are checked for > 0 and then later checked for == 0.  This code should be investigated and possibly rewritten.

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Replace `wingp->num_waves == 0` with valid `wingp->current_wave >= wingp->num_waves` and correct a six year old copy paste error.

This will need testing to make sure it helps red alert work as expected.

Because this is basically contrary to how it has worked for 22.2 up to now, and it might disrupt some mod development somewhere, I am putting a waiting for stable flag on it.

closes #4269

### CODE REVIEW

**Review by Goober5000 — DISMISSED** [review]
This looks good to me

**Comment by JohnAFernandez** [comment]
It is probably correct.  The only thing keeping this in draft is a sanity test to make sure it works as expected.  My testing set up has been non existent going on 6 months.  (pre built laptop fell apart after about a year of use)

**Comment by JohnAFernandez** [comment]
Ok, based on discussions with dahblount on discord, our new approach is to save wing info separately to make sure wing info persists properly.

File: code/missionui/redalert.cpp [hunk 1]
```diff
@@ -787,6 +788,45 @@ void red_alert_store_wingman_status()
...
+
+	// Cyborg - imho, clearing data before trying to record the current mission's data is the right move, 
+	// pretty much no matter what.
+	Red_alert_wing_status.clear();
+
+	for (const auto& recorded_wing : temp_wing_status) {
+		// only allow a wing's status to carry over if all of the ships were marked.
+		if (recorded_wing.number_of_ships_marked == recorded_wing.max_ships_per_wave)
+			Red_alert_wing_status.push_back(recorded_wing);
+	}
```
Comment (Goober5000) [inline code/missionui/redalert.cpp:827]: This should probably have a warning for the benefit of mission designers
```suggestion
		// only allow a wing's status to carry over if all of the ships were marked.
		if (recorded_wing.number_of_ships_marked == recorded_wing.max_ships_per_wave)
			Red_alert_wing_status.push_back(recorded_wing);
		else
			Warning(LOCATION, "Not all ships in %s were marked with \"red-alert-carry\".  The wing will not be stored.", recorded_wing.wing_name.c_str());
	}
```

File: code/missionui/redalert.cpp [hunk 2]
```diff
@@ -1034,7 +1076,9 @@ void red_alert_bash_wingman_status()
 			wingp->current_wave++;
 			wingp->red_alert_skipped_ships += wingp->wave_count;
 
-            if (wingp->num_waves == 0)
+			bool waves_spent = wingp->current_wave >= wingp->num_waves;
```
Comment (Goober5000) [inline code/missionui/redalert.cpp:1079]: I think this should be >, not >=.  The `current_wave` field is 1-based.
```suggestion
			bool waves_spent = wingp->current_wave > wingp->num_waves;
```

File: code/missionui/redalert.cpp [hunk 3]
```diff
@@ -1055,6 +1099,38 @@ void red_alert_bash_wingman_status()
...
+
+		for (int i = 0; i < MAX_WINGS; ++i){
+			auto& mission_wing = Wings[i];
+
+			// check that we have the same wing.  Then we check if the wings are actually compatible.
+			if (!stricmp(recorded_wing.wing_name.c_str(), mission_wing.name)){
+
+				// do we have sufficient waves in the current mission to handle where the wave should be from the previous mission?
+				if  ((mission_wing.num_waves < recorded_wing.current_wave) || (mission_wing.wave_count != recorded_wing.max_ships_per_wave)){
+					mprintf(("Red alert code cannot restore %s wing's info since there's a mismatch of total ships available (total waves and ships per wave). New ships for this wing will not appear.", mission_wing.name));
```
Comment (Goober5000) [inline code/missionui/redalert.cpp:1114]: This should be a warning
```suggestion
					Warning(LOCATION, "Red alert code cannot restore %s wing's info since there's a mismatch of total ships available (total waves and ships per wave). New ships for this wing will not appear.", mission_wing.name);
```

File: code/missionui/redalert.h [hunk 4]
```diff
@@ -52,7 +54,25 @@ typedef struct red_alert_ship_status {
...
 } red_alert_ship_status;
 
+typedef struct red_alert_wing_status {
+	SCP_string wing_name;
+	int max_ships_per_wave; // how many ships per wave.  If this doesn't match, then we have to ignore this info
+	int wave_count; // Put this in for now, too.  The max number of waves for this wing. 
+	int current_wave; // 1-based index for which wave we are currently on out of the total
+	int number_of_ships_marked; // if the number of ships marked does not end up being the same as the entire wave, then we don't keep this  
+
+	red_alert_wing_status(SCP_string wing_name_in, int max_ships_in, int wave_count_in, int current_wave_in, int number_of_ships_marked_in){
```
Comment (Goober5000) [inline code/missionui/redalert.h:64]:
```suggestion
	red_alert_wing_status(const SCP_string &wing_name_in, int max_ships_in, int wave_count_in, int current_wave_in, int number_of_ships_marked_in){
```

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Some comments

**Review by TRBlount — APPROVED** [review]
