### PR TITLE
Fix erroneous line break generation for non-ASCII string and high resolutions

### LINKED ISSUE #3438: FR: Max briefing text size could be increased
I have been messing with the Japanese Translation on NTP, but the translation always CTDs during certain command briefing stages due to
Assert: "n_chars[i] < MAX_BRIEF_LINE_LEN"
File: missionbriefcommon.cpp
Line: 1701

Based on the variable name I am seeing, I am assuming that the translation text has tripped the maximum text length for briefings. If this limit could be extended, that would be appreciated.

### PR DESCRIPTION
**Pull request by BMagnu**
FSO's function to automatically linebreak text was previously only looking at the line lengths in pixels, and copying that into fixed length buffers. Hence, if you had characters using a lot of bytes per width (like in the NTP's Japanese translation with Kanjis) or a high resolution resulting in more characters per line being displayable (this is conjecture only, I haven't actually tested that this was an error before, but I am fairly certain it was), many functions using this linebreak functions could trip asserts, or worse, overrun their buffers causing CTD's. Thus, this also fixes #3438.
For the briefing parts specifically I also increased the buffer size, as this is a relatively safe thing to do, and otherwise lines could be broken earlier than the screens end, which is ugly (but not a CTD anymore).
I severely hope to not have missed any uses of this function, that would also need a specific maximum buffer length set.

### CODE REVIEW

File: code/network/multiui.cpp [hunk 1]
```diff
@@ -234,13 +234,11 @@ void multi_common_split_text()
 	int	n_chars[MAX_BRIEF_LINES];
 	const char	*p_str[MAX_BRIEF_LINES];
 
-	n_lines = split_str(Multi_common_all_text, Multi_common_text_coords[gr_screen.res][2], n_chars, p_str, MULTI_COMMON_TEXT_MAX_LINES, MULTI_COMMON_TEXT_META_CHAR);
+	n_lines = split_str(Multi_common_all_text, Multi_common_text_coords[gr_screen.res][2], n_chars, p_str, MULTI_COMMON_TEXT_MAX_LINES, MULTI_COMMON_TEXT_MAX_LINE_LENGTH, MULTI_COMMON_TEXT_META_CHAR);
 	Assert(n_lines != -1);
 
 	for ( i = 0; i < n_lines; i++ ) {
-		//The E -- This check is unnecessary, and will break when fonts that aren't bank gothic are used
```
Comment (BMagnu) [inline code/network/multiui.cpp:241]: Just as a note as to why I removed this comment and readded the Assertion:
The assert here does _not_ check for string width in pixels or anything. 
It just checks that the string, in bytes, fits the buffer. Which is an essential Assertion, and that this is missing in other places where this string split was used is the reason that it didn't assert but CTD.
While the new function should always avoid this case, it's still a sensible assert, should that function ever be reworked

File: code/menuui/optionsmenumulti.cpp [hunk 2]
```diff
@@ -656,7 +656,7 @@ void options_multi_notify_process()
 
 	// otherwise display the string
 	line_height = gr_get_font_height() + 1;
-	line_count = split_str(Om_notify_string, 600, n_chars, p_str, 3);	
+	line_count = split_str(Om_notify_string, 600, n_chars, p_str, 3, 255);
```
Comment (Goober5000) [inline code/menuui/optionsmenumulti.cpp:659]: The 255 should be a `#define` or `const`, not a hardcoded number.

File: code/network/multi_pxo.cpp [hunk 3]
```diff
@@ -3248,7 +3248,7 @@ void multi_pxo_chat_process_incoming(const char *txt,int mode)
 	}
 
 	// split the text up into as many lines as necessary
-	n_lines = split_str(msg_total, Multi_pxo_chat_coords[gr_screen.res][2] - 5, n_chars, p_str, 3);
+	n_lines = split_str(msg_total, Multi_pxo_chat_coords[gr_screen.res][2] - 5, n_chars, p_str, 3, 512);
```
Comment (Goober5000) [inline code/network/multi_pxo.cpp:3251]: Same with the 512.

**Review by Goober5000 — CHANGES_REQUESTED** [review]

File: code/mission/missionbriefcommon.cpp [hunk 4]
```diff
@@ -1681,7 +1681,7 @@ int brief_color_text_init(const char* src, int w, const char default_color, int
 	}
 
 	Assert(src != NULL);
-	n_lines = split_str(src, w, n_chars, p_str, BRIEF_META_CHAR);
+	n_lines = split_str(src, w, n_chars, p_str, MAX_BRIEF_LINE_LEN, BRIEF_META_CHAR, true);
```
Comment (Goober5000) [inline code/mission/missionbriefcommon.cpp:1684]: I don't think leading whitespace should be stripped.  Some briefings may use whitespace-aligned text.

File: code/network/multiui.cpp (hunk 1 above)
Comment (Goober5000) [reply code/network/multiui.cpp:241]: Good reasoning, but you should test this PR on non-BankGothic fonts to make sure you're not missing anything.

File: code/parse/parselo.cpp [hunk 5]
```diff
@@ -3419,7 +3419,7 @@ int split_str(const char *src, int max_pixel_w, int *n_chars, const char **p_str
 		buffer[buf_index] = 0;  // null terminate it
 
 		gr_get_string_size(&sw, NULL, buffer);
-		if (sw >= max_pixel_w) {
+		if (sw >= max_pixel_w || buf_index >= max_line_length) {
```
Comment (Goober5000) [inline code/parse/parselo.cpp:3422]: Should this check for length-1?  You have to account for not only the number of bytes but also the null terminator.

File: code/parse/parselo.cpp [hunk 6]
```diff
@@ -3542,7 +3542,7 @@ int split_str(const char *src, int max_pixel_w, SCP_vector<int> &n_chars, SCP_ve
...
```
Comment (Goober5000) [inline code/parse/parselo.cpp:3545]: Ditto

**Review by Goober5000 — COMMENTED** [review]
A few more comments

File: code/mission/missionbriefcommon.cpp (hunk 4 above)
Comment (BMagnu) [reply code/mission/missionbriefcommon.cpp:1684]: This, as this true is the default argument, would be a change to the current behaviour.
I agree with your reasoning, but should we really change established behaviour for this?

File: code/parse/parselo.cpp (hunk 5 above)
Comment (BMagnu) [reply code/parse/parselo.cpp:3422]: Hence I check >= and not >.
If, with the char already added, the length of the string is equal to the buffer size (and thus would fill the buffer exactly with no \0), it will be rolled back until the last separator (or by one).
Should work like this

File: code/network/multiui.cpp (hunk 1 above)
Comment (BMagnu) [reply code/network/multiui.cpp:241]: Tbh, testing this very line is hard for me, as it's a part of multi and I have no clue how to actually get into a mission with a specific mod to test this assertion.
However, I would advocate for that being unnecessary anyways:
definition of the array we srncpy into:
``char Multi_common_text[MULTI_COMMON_TEXT_MAX_LINES][MULTI_COMMON_TEXT_MAX_LINE_LENGTH];``
definition of the assert
``Assert(n_chars[i] < MULTI_COMMON_TEXT_MAX_LINE_LENGTH); ``
strncpy in question:
``strncpy(Multi_common_text[i], p_str[i], n_chars[i]);``

Even if, somehow, that Assert had anything to do with linesize, if it would be triggered here (and be commented out), it would _always_ cause a CTD, unless that string to be copied contains magical \0's. And an assert (with broken fonts) is always better than a CTD (with broken fonts).

Comment (Goober5000) [reply code/network/multiui.cpp:241]: Ok

File: code/mission/missionbriefcommon.cpp (hunk 4 above)
Comment (Goober5000) [reply code/mission/missionbriefcommon.cpp:1684]: I didn't realize `true` was default.  In that case, don't change established behavior, but also it's probably better not to add the optional argument.

File: code/parse/parselo.cpp (hunk 5 above)
Comment (Goober5000) [reply code/parse/parselo.cpp:3422]: Ok

**Review by Goober5000 — APPROVED** [review]
Looks good

File: code/mission/missionbriefcommon.cpp (hunk 4 above)
Comment (BMagnu) [reply code/mission/missionbriefcommon.cpp]: ok, cleaned that up

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Just make the one change to remove the default `true`

**Review by Goober5000 — APPROVED** [review]
