### PR TITLE
fix nebula range in mission-set-nebula

### LINKED ISSUE #3619: Nebula mission vs toggle-nebula SEXP targeting issues
When you specify a mission as a Nebula mission in the Background editor, an AWACs is not required in-mission to target hostiles. It uses some % of the range specified in the background editor.

If you use a sexp to toggle nebula on mid-mission it seems like you must have an AWACs present or you can't target hostiles. I'm aware there's a sexp to set AWACs distance but it's arguments require you to specify a ship first.

### PR DESCRIPTION
**Pull request by Goober5000**
The mission-set-nebula sexp never initialized the nebula range, which is usually done in the background editor.  This PR allows the range to be specified, and sets it to 3000 (the same default as in the background editor) if not specified.

Fixes #3619.

### CODE REVIEW

File: code/starfield/starfield.cpp [hunk 1]
```diff
@@ -2517,27 +2517,27 @@ const char *stars_get_name_from_instance(int index, bool is_a_sun)
...
-			stars_set_background_model(BACKGROUND_MODEL_FILENAME, Neb2_texture_name);
-			stars_set_background_orientation();
-		} else {
-			Neb2_render_mode = NEB2_RENDER_HTL;
-		}
+
+		Neb2_render_mode = NEB2_RENDER_HTL;
+		Neb2_awacs = range;
+		if (Neb2_awacs < 0.1f)
+			Neb2_awacs = 3000.0f;
```
Comment (jg18) [inline code/starfield/starfield.cpp:2532]: Can you add a comment on where this number comes from?

File: code/starfield/starfield.cpp [hunk 2]
```diff
@@ -2517,27 +2517,27 @@ const char *stars_get_name_from_instance(int index, bool is_a_sun)
...
-void stars_set_nebula(bool activate)
+void stars_set_nebula(bool activate, float range)
 {
     The_mission.flags.set(Mission::Mission_Flags::Fullneb, activate);
 	
     if (activate)
 	{
 		Toggle_text_alpha = TOGGLE_TEXT_NEBULA_ALPHA;
 		HUD_contrast = 1;
-		if(Fred_running) {
```
Comment (jg18) [inline code/starfield/starfield.cpp:2528]: I'm unclear on why special treatment while FRED is running is no longer needed?

**Review by jg18 — APPROVED** [review]
A couple small things but seems reasonable overall.

File: code/starfield/starfield.cpp (hunk 1 above)
Comment (Goober5000) [reply code/starfield/starfield.cpp:2532]: Done

File: code/starfield/starfield.cpp (hunk 2 above)
Comment (Goober5000) [reply code/starfield/starfield.cpp:2528]: Because the function is never called from FRED.  I suppose it doesn't hurt to put this back in, though, if that were ever changed.
