### PR TITLE
Warn dogfight weapons

### LINKED ISSUE #3100: FRED Should prevent dogfight missions that don't have dogfight weapons allowed.
Migrated Mantis issue 2107.

Load up this mission in multi and you will find you cannot play it because there are no allowed weapons. Dogfight missions need dogfight weapons.

Notably the crash reported in the original Mantis ticket is no longer an issue. This is now just something that FRED should warn the FREDer about.

[Untitled2.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5790337/Untitled2.zip)

### PR DESCRIPTION
**Pull request by MjnMixael**
Fixes #3100 and Mantis 2107 by doing a quick check for dogfight weapons for each ship in the loadout if the mission is a dogfight mission. If not at least one weapon for each ship type then show a warning.

### CODE REVIEW

File: qtfred/src/mission/missionsave.cpp [hunk 1]
```diff
@@ -3757,6 +3758,17 @@ int CFred_mission_save::save_players()
...
+				// Check the weapons pool for at least one dogfight weapon for this ship type
+				if (IS_MISSION_MULTI_DOGFIGHT) {
+					for (int wepCount = 0; wepCount <= Team_data[i].num_weapon_choices; wepCount++) {
+						if (Ship_info[Team_data[i].ship_list[j]].allowed_weapons[Team_data[i].weaponry_pool[wepCount]] &
+							DOGFIGHT_WEAPON) {
+							num_dogfight_weapons++;
+							break;
+						}
+					}
+				}
```
Comment (JohnAFernandez) [inline qtfred/src/mission/missionsave.cpp:3771]: Based on how I'm reading it, this new code should be outside the if that it is nested in.  I'm reading that we're only checking for a class if someone specified a concrete count instead of a variable based count.  Shouldn't it be checked regardless?

File: qtfred/src/mission/missionsave.cpp [hunk 2]
```diff
@@ -3773,6 +3785,13 @@ int CFred_mission_save::save_players()
 
 		fout(")");
 
+		// make sure we have at least one dogfight weapon for each ship type in a dogfight mission
+		if (IS_MISSION_MULTI_DOGFIGHT && (num_dogfight_weapons != Team_data[i].num_ship_choices)) {
+			MessageBox(nullptr,
+				"Warning: This mission is a dogfight mission but no dogfight weapons are available for at least one ship in the loadout!", "No dogfight weapons",
+				MB_OK);
+		}
```
Comment (JohnAFernandez) [inline qtfred/src/mission/missionsave.cpp:3793]: Suggestion if you have the skill to pull it off: record the ships that don't have dogfight weapons available and then add them to this warning.  An `SCP_string` would make the process fairly easy.

**Review by JohnAFernandez — CHANGES_REQUESTED** [review]

File: qtfred/src/mission/missionsave.cpp (hunk 2 above)
Comment (MjnMixael) [reply qtfred/src/mission/missionsave.cpp:3793]: The number of ships this could include is technically unlimited, making the error message potentially incredibly long. Otherwise I'd do it.

Instead it's probably better to print each ship to the log and include that instruction in the message itself.

Comment (JohnAFernandez) [reply qtfred/src/mission/missionsave.cpp:3793]: Ah, smart.

File: qtfred/src/mission/missionsave.cpp (hunk 1 above)
Comment (MjnMixael) [reply qtfred/src/mission/missionsave.cpp]: Yes you're right. Done

File: qtfred/src/mission/missionsave.cpp (hunk 2 above)
Comment (MjnMixael) [reply qtfred/src/mission/missionsave.cpp:3801]: and done

File: fred2/missionsave.cpp [hunk 3]
```diff
@@ -3966,10 +3969,34 @@ int CFred_mission_save::save_players()
 			} else {
 				fout("%d\n", Team_data[i].ship_count[j]);
 			}
+
+			// Check the weapons pool for at least one dogfight weapon for this ship type
+			if (IS_MISSION_MULTI_DOGFIGHT) {
+				for (int wepCount = 0; wepCount <= Team_data[i].num_weapon_choices; wepCount++) {
```
Comment (Goober5000) [inline fred2/missionsave.cpp:3975]: I believe this `<=` should be `<`

File: qtfred/src/mission/missionsave.cpp [hunk 4]
```diff
@@ -3769,10 +3772,34 @@ int CFred_mission_save::save_players()
 			} else {
 				fout("%d\n", Team_data[i].ship_count[j]);
 			}
+
+			// Check the weapons pool for at least one dogfight weapon for this ship type
+			if (IS_MISSION_MULTI_DOGFIGHT) {
+				for (int wepCount = 0; wepCount <= Team_data[i].num_weapon_choices; wepCount++) {
```
Comment (Goober5000) [inline qtfred/src/mission/missionsave.cpp:3778]: Same here

**Review by Goober5000 — CHANGES_REQUESTED** [review]

File: fred2/missionsave.cpp (hunk 3 above)
Comment (MjnMixael) [reply fred2/missionsave.cpp]: done

File: qtfred/src/mission/missionsave.cpp (hunk 4 above)
Comment (MjnMixael) [reply qtfred/src/mission/missionsave.cpp]: done

**Review by Goober5000 — APPROVED** [review]

**Review by JohnAFernandez — APPROVED** [review]
