### PR TITLE
Get rid of OpenGL warnings about the framebuffer being unsupported.

### LINKED ISSUE #1382: Nvidia drivers output a lot of OpenGL debug warnings
The Nvidia driver prints the following message via the OpenGL debug interface:
```
Framebuffer unsupported. Framebuffer object Scene framebuffer is unsupported because the depth and stencil attachments are mismatched.
```

@MageKing17 found the source of the warning. Here is the stacktrace:
```
>	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!debug_callback(unsigned int source=33350, unsigned int type=33361, unsigned int id=65536, unsigned int severity=37191, int length=134, const char * message=0x0000000059ece490, const void * userParam=0x0000000000000000) Line 1371	C++
 	nvoglv64.dll!000000005897feab()	Unknown
 	nvoglv64.dll!000000005874aa1f()	Unknown
 	nvoglv64.dll!000000005874ab0c()	Unknown
 	nvoglv64.dll!000000005874aab5()	Unknown
 	nvoglv64.dll!0000000058759a49()	Unknown
 	nvoglv64.dll!000000005875aea2()	Unknown
 	nvoglv64.dll!00000000587c1a4a()	Unknown
 	nvoglv64.dll!0000000058b29972()	Unknown
 	nvoglv64.dll!00000000587510b2()	Unknown
 	nvoglv64.dll!0000000058750138()	Unknown
 	nvoglv64.dll!0000000058755db5()	Unknown
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!gr_opengl_deferred_lighting_finish() Line 2202	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!obj_render_queue_all() Line 394	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!game_render_frame(camid cid={...}) Line 3428	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!game_frame(bool paused=false) Line 4123	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!game_do_frame() Line 4498	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!game_do_state(int state=2) Line 6197	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!gameseq_process_events() Line 404	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!game_main(int argc=1, char * * argv=0x00000000005505b0) Line 6736	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!actual_main(int argc=1, char * * argv=0x00000000005505b0) Line 7925	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!SDL_main(int argc=1, char * * argv=0x00000000005505b0) Line 7971	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!main_utf8(int argc=1, char * * argv=0x00000000005505b0) Line 127	C
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!WinMain(HINSTANCE__ * hInst=0x0000000140000000, HINSTANCE__ * hPrev=0x0000000000000000, char * szCmdLine=0x0000000000564538, int sw=10) Line 191	C
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!invoke_main() Line 99	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!__scrt_common_main_seh() Line 253	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!__scrt_common_main() Line 296	C++
 	fs2_open_3_7_5_x64_AVX2-DEBUG.exe!WinMainCRTStartup() Line 17	C++
 	kernel32.dll!00007ff9b74e2774()	Unknown
 	ntdll.dll!00007ff9b7990d61()	Unknown
```

I think the call that causes the warning should be valid but it may be that the Nvidia drivers don't like mixing framebuffers with and without a stencil attachment which may be happening in our code. 
@SamuelCho Do you have any idea why this could be happening?

### PR DESCRIPTION
**Pull request by MageKing17**
At least on NVidia drivers, the medium-severity warning "Framebuffer unsupported. Framebuffer object Scene framebuffer is unsupported because the depth and stencil attachments are mismatched." would get repeatedly output to the debug log. @SamuelCho suggested this change, which gets rid of the warnings and doesn't appear to have introduced any graphical glitches.

Fixes #1382.

### CODE REVIEW

File: code/graphics/opengl/gropengldraw.cpp [hunk 1]
```diff
@@ -2198,7 +2198,7 @@ void gr_opengl_deferred_lighting_finish()
 	}
 
 	glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, Scene_color_texture, 0);
-	glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, Scene_depth_texture, 0);
+	glFramebufferTexture2D(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_TEXTURE_2D, Scene_depth_texture, 0);
 	glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_RENDERBUFFER, 0);
```
Comment (asarium) [inline code/graphics/opengl/gropengldraw.cpp]: This line should be `glFramebufferTexture2D(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_TEXTURE_2D, 0)`. The line above should be fine (I think).

**Comment by MageKing17** [comment]
> glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, Scene_depth_texture, 0) needs to stay.

...That's the line generating the warning, though? If I revert that change and change line 2202 as you specified (and why don't we need to call `glFramebufferRenderbuffer()`?), the warning is generated every frame again.

**Comment by SamuelCho** [comment]
DEPTH_ATTACHMENT needs to still be bound to the Scene_depth_texture, otherwise we won't be able to write to the scene depth buffer anymore. We don't need a stencil buffer at that point anymore but we definitely still need a depth buffer.

If my solution isn't working, then I'll have to investigate further on my own when I have time.

**Comment by MageKing17** [comment]
Did you see my edit? If that solution is acceptable, I'll update the PR with that.

**Comment by SamuelCho** [comment]
Yeah that's better. That should allow us to still use the depth buffer.

**Comment by MageKing17** [comment]
Commit amended.
