### PR TITLE
Keep fred from adding extra texture replacements to mission file

### LINKED ISSUE #3069: Texture replacements make FRED repeat itself.
This is one that's been present for a while but I haven't filed because I haven't ever pinned down repro steps when I tried. I still haven't, but here it is anyway.

When there's a ship in a mission file with tabled texture replacements, something makes FRED add the texture replacements to the mission file. I don't know if that's needed or not, but even if it does, it keeps adding them even when they're already there. I don't know what makes it do this, I haven't 'caught' it doing it at specific times like whenever you save or anything like that, I have just occasionally glanced at the diffs for a mission before commiting them to a dev repository, and seen the growing list of replacements. 

For example, this is from the table of the SD Vritra
```
$POF file:                      Ravana.pof
$Texture Replace:		
	+old: Ravana01-Glow.dds
	+new: adv-Ravana01-Glow.png
	+old: Ravana02-Glow.dds
	+new: adv-Ravana02-Glow.png
	+old: RavanaDet-Glow.dds
	+new: adv-RavanaDet-Glow.png
	+old: Ravana03-Glow.dds
	+new: adv-Ravana03-Glow.png
	+old: RavanaPulse.dds
	+new: adv-RavanaPulse.png
	+old: STurrets01-Glow.dds
	+new: adv-STurrets01-Glow.png
	+old: RavDead01-Glow.dds
	+new: adv-RavDead01-Glow.png
	+old: RavDead02-Glow.dds
	+new: adv-RavDead02-Glow.png
```
and this is an entry from a mission I've been working on for a while including a Vritra
```
$Name: SD Vritra		;! Object #53
$Class: SD Vritra
$Team: Hostile
$Location: -32478.000000, 965.600769, -5160.549805
$Orientation:
	0.991562, 0.000000, -0.129634,
	0.009067, 0.997552, 0.069353,
	0.129317, -0.069943, 0.989135
$AI Behavior: None
$AI Goals: ( goals ( ai-chase "GTCv Osaka#2" 80 ) ( ai-chase "GTD Delhi#2" 50 ) )
$Cargo 1:  XSTR("Nothing", -1)
+Initial Velocity: 33
+Initial Hull: 100
+Initial Shields: 100
+Subsystem: Pilot
+Subsystem: Turret01
+Subsystem: Turret02
+Subsystem: Turret03
+Subsystem: Turret04
+Subsystem: Turret05
+Subsystem: Turret06
+Subsystem: Turret07
+Subsystem: Turret08
+Subsystem: Turret09
+Subsystem: Turret10
+Subsystem: Turret11
+Subsystem: Turret12
+Subsystem: Turret13
+Subsystem: Turret14
+Subsystem: Turret15
+Subsystem: Turret16
+Subsystem: Turret17
+Subsystem: Turret18
+Subsystem: Turret19
+Subsystem: Turret20
+Subsystem: Turret21
+Subsystem: Turret22
+Subsystem: Turret23
+Subsystem: Turret24
+Subsystem: Turret25
+Subsystem: Turret26
+Subsystem: Turret27
+Subsystem: Turret28
+Subsystem: Turret29
+Subsystem: Turret30
$Arrival Location: Hyperspace
+Arrival Delay: 15
$Arrival Cue: ( and 
   ( has-arrived-delay 0 "Beta" ) 
   ( < ( num-ships-in-battle "Beta" ) 2 ) 
)
$Departure Location: Hyperspace
$Departure Cue: ( false ) 
$Determination: 10
+Flags: ( "no-shields" )
+Flags2: ( )
+Respawn priority: 0
+Orders Accepted: 0		;! note that this is a bitfield!!!
+Group: 0
+Use Table Score:
+Score: 670
$Texture Replace:
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
+old: Ravana01-Glow
+new: adv-Ravana01-Glow
+old: Ravana02-Glow
+new: adv-Ravana02-Glow
+old: RavanaDet-Glow
+new: adv-RavanaDet-Glow
+old: Ravana03-Glow
+new: adv-Ravana03-Glow
+old: RavanaPulse
+new: adv-RavanaPulse
+old: STurrets01-Glow
+new: adv-STurrets01-Glow
+old: RavDead01-Glow
+new: adv-RavDead01-Glow
+old: RavDead02-Glow
+new: adv-RavDead02-Glow
```

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Adds a way for fred to distinguish whether texture replacements are from the table or from the mission file/ship texture dialog, by adding a bool to the struct.

Fixes #3069

### CODE REVIEW

File: qtfred/src/mission/missionsave.cpp [hunk 1]
```diff
@@ -3395,7 +3395,8 @@ int CFred_mission_save::save_objects()
 
 			for (SCP_vector<texture_replace>::iterator ii = Fred_texture_replacements.begin();
 				 ii != Fred_texture_replacements.end(); ++ii) {
-				if (!stricmp(shipp->ship_name, ii->ship_name)) {
+				// Only look at this entry if it's not from the table. Table entries will just be read by FSO.
+				if (!stricmp(shipp->ship_name, ii->ship_name) && (!ii->from_table)) {
```
Comment (Goober5000) [inline qtfred/src/mission/missionsave.cpp:3399]: Looks good, except here you use `(!ii->from_table)` while everywhere else you use `!(ii->from_table)`.  Do you want to standardize on one format?

Comment (JohnAFernandez) [reply qtfred/src/mission/missionsave.cpp:3399]: I knew I had done it differently at some point....

**Review by Goober5000 — APPROVED** [review]
