### PR TITLE
Don't kill paused messages

### LINKED ISSUE #6168: as.pauseVoiceMessages() doesn't always unpause messages that were playing
Basically that. Pausing works. Unpausing sometimes doesn't work. I'm guessing the files reached some sort of timer and were released or something.

### PR DESCRIPTION
**Pull request by MjnMixael**
Fixes #6168 by adding an explicit check for paused messages. If they are paused then we shouldn't kill them.

### CODE REVIEW

File: code/mission/missionmessage.cpp [hunk 1]
```diff
@@ -1449,6 +1449,11 @@ void message_queue_process()
 			if ((Playing_messages[i].wave.isValid()) && (snd_time_remaining(Playing_messages[i].wave) > 250))
 				wave_done = 0;
 
+			// Don't kill paused messages
+			if ((Playing_messages[i].wave.isValid()) && snd_is_paused(Playing_messages[i].wave)) {
```
Comment (wookieejedi) [inline code/mission/missionmessage.cpp:1453]: Nice fix, sorry to be nitpicky but if you feel so inclined this could be an or check with the above if, though I reckon you kept them separate for readability.

Comment (MjnMixael) [reply code/mission/missionmessage.cpp:1453]: I did that originally but yeah I thought this was easier to read and there was already precedent for multiple statements that set `wave_done = 0`

Comment (wookieejedi) [reply code/mission/missionmessage.cpp:1453]: I'm good with it as is, if someone else really wants to have it be an OR then they can let us know.

**Review by JohnAFernandez — APPROVED** [review]
I'm good with it separate because there's already another similar check lower.  Compiler will probably combine them.

**Review by wookieejedi — APPROVED** [review]
