### PR TITLE
Fix Lua API polluting the game context

### LINKED ISSUE #4815: Setting `gr.CurrentFont` or using `gr.setLineWidth` pollute FSO's graphics context
Probably others too. Presumably depending on when you call them, changing the `CurrentFont` or setting the line width will propagate those changes even to lines and text drawn by FSO itself, and messing up a bunch of visuals. It's understandable why this happens due to the way they are implemented, but it is very cumbersome and annoying to constantly remember to have to save the old value for these, make your changes, draw your graphics, and then put them back. FSO should either do this automatically, or the usages of lines and text should set the font/line width themselves to they values they intend (rather assume they are correct).

### PR DESCRIPTION
**Pull request by MjnMixael**
I was working on some lua scripts and once again got annoyed by having to save color and font values to restore them when I'm done drawing with Lua. So I whipped up this draft idea as a possible way to solve the issue. This creates `gr_lua_screen` with relevant members. Setting the color, font, or line width from Lua will, by default, only set the members of that struct. Calling drawing methods from Lua, by default, will use the members of that struct. I left in a way to override and set/use the game context values as well but I'm not really certain how useful that is or if it just muddies up the API a bit.

This is all very much draft status and mostly just wanting to get feedback if this is worth cleaning up and implementing in full.

Fixes #4815

### CODE REVIEW

**Comment by MjnMixael** [comment]
> As for the implementation, you might consider toggling the context via a separate function or variable, rather than having new optional arguments on all these functions.

That's an interesting idea. Do you think there's much need for Lua to mess with the game's internal context? I couldn't think of one but it's hard to know what everyone's done in the past. 

Personally I'd even be ok with disallowing Lua to get or set anything outside of the Lua context.

**Comment by Baezon** [comment]
I would be too, but it's hard to think of all the uses cases.  One hand, it was possible before so it'd be a shame to 'take it away', but my general line-in-the-sand for not providing some functionality is when its misuse (or just use) can cause mysterious problems which are difficult to diagnose or workaround on their end, which I'd probably classify this 'polluted context' as. I don't feel particularly strongly one way or the other.

**Comment by MjnMixael** [comment]
> I would be too, but it's hard to think of all the uses cases. One hand, it was possible before so it'd be a shame to 'take it away', but my general line-in-the-sand for not providing some functionality is when its misuse (or just use) can cause mysterious problems which are difficult to diagnose or workaround on their end, which I'd probably classify this 'polluted context' as. I don't feel particularly strongly one way or the other.

Ok, so I added a couple bools to the lua context to track what we're doing which simplifies a lot of the parameters passed around. It's not my preferred way but it matches how we use `gr_screen` a bit so I guess that works. I also added a virtvar to set a context override. Tell me what you think of this version.

**Comment by Baezon** [comment]
Yep, I'd be happy with this approach.

**Comment by wookieejedi** [comment]
Awesome to see this as ready for review, will make scripting in this area so much cleaner.

File: code/graphics/2d.h [hunk 1]
```diff
@@ -935,6 +935,42 @@ typedef struct screen {
...
+extern lua_screen gr_lua_screen;
+
+bool gr_lua_context_active();
+
+// Macros to easily choose been which context to use for color and line width
+// Note that font is handled slightly differently for the normal game context by using it's own global in the FontManager namespace
+// So FontManager::getCurrentFontIndex() is effectively its own macro
+
+// Gets the current color between the game context and the lua context if active
+#define GR_CURRENT_COLOR (gr_lua_context_active() ? &gr_lua_screen.current_color : &gr_screen.current_color)
```
Comment (Baezon) [inline code/graphics/2d.h]: My gut says the macro shouldn't do the address `&`, so the macro just represents the underlying variable as is, then each situation uses address or not as appropriate. This way the macro can be used exactly as the variable was before, and coders later don't have to remember whether or not this is a pointer.

File: code/graphics/opengl/gropengl.cpp [hunk 2]
```diff
@@ -787,10 +787,15 @@ void gr_opengl_zbias(int bias)
 
 void gr_opengl_set_line_width(float width)
 {
-	if (width <= 1.0f) {
-		GL_state.SetLineWidth(width);
+	if (gr_lua_context_active()) {
+		gr_lua_screen.line_width = width;
+	} else {
+		if (width <= 1.0f) {
+			GL_state.SetLineWidth(width);
```
Comment (Baezon) [inline code/graphics/opengl/gropengl.cpp:794]: Does this need to be applied to the lua context case too?

File: code/scripting/api/libs/graphics.cpp [hunk 3]
```diff
@@ -1166,15 +1227,15 @@ ADE_FUNC(drawTargetingBrackets, l_Graphics, "object Object, [boolean draw=true,
 ADE_FUNC(
     drawSubsystemTargetingBrackets, l_Graphics, "subsystem subsys, [boolean draw=true, boolean setColor=false]",
     "Gets the edge position of the targeting brackets drawn for a subsystem as if they were drawn on the HUD. Only "
-    "actually draws the brackets if <i>draw</i> is true, optionally sets the color the as if it was drawn on the HUD",
+    "actually draws the brackets if <i>draw</i> is true, optionally sets the color the as if it was drawn on the HUDcurrent using active context color",
```
Comment (Baezon) [inline code/scripting/api/libs/graphics.cpp]:
```suggestion
    "actually draws the brackets if <i>draw</i> is true, optionally sets the color if it was drawn on the HUD using active context color",
```

File: code/scripting/api/libs/graphics.cpp [hunk 4]
```diff
@@ -1157,6 +1216,8 @@ ADE_FUNC(drawTargetingBrackets, l_Graphics, "object Object, [boolean draw=true,
 		line_draw_list.flush();
 	}
 
+	gr_lua_screen.active = false;
```
Comment (Baezon) [inline code/scripting/api/libs/graphics.cpp]: This should come after the `g3_end_frame()` below to match its other usages. I don't think it happens to matter in this case, but it could in the future and make for a nasty surprise.

**Review by Baezon — CHANGES_REQUESTED** [review]
Ok, took a closer look at it now that it's ready for review.

File: code/graphics/opengl/gropengl.cpp (hunk 2 above)
Comment (MjnMixael) [reply code/graphics/opengl/gropengl.cpp:794]: It wasn't before and I'm honestly not sure what the implications of it are so I opted to keep behavior the same.

File: code/scripting/api/libs/graphics.cpp (hunk 4 above)
Comment (MjnMixael) [reply code/scripting/api/libs/graphics.cpp]: Good call. I've addressed this and I think everything else.

File: code/graphics/opengl/gropengl.cpp (hunk 2 above)
Comment (Baezon) [reply code/graphics/opengl/gropengl.cpp:794]: Fair enough.

**Review by Baezon — APPROVED** [review]
Apparently, screen scale and the clip rect have a similar situation going on, did you have any other plans in that regard?

**Comment by MjnMixael** [comment]
> I think its fine to merge this and have a follow-up PR. They've got the same sort of set a thing, then reset it situation. You can see in `gr_reset_screen_scale()` the engine maintains a bunch of 'save' variables for this purpose, which isn't the prettiest.

Sounds good. I'll handle that once this is merged.
