### PR TITLE
Fix nested and animated submodel collisions

### LINKED ISSUE #3985: Assertion relating to animated submodels
BtA has encountered this Assert 

Assert: "pm->submodel[submodel_num].movement_type == MOVEMENT_TYPE_ROT || pm->submodel[submodel_num].movement_type == MOVEMENT_TYPE_INTRINSIC"

The model in question has two animated submodels. They are doors that use animation type Rotation on docking-stage-2 to open and animation type Rotation on Docked to close. Looks like the Assert happened as the ship was going down, possibly while in the middle of docking or undocking. Relevant log is attached.

Animation details are here. And I verified that the submodels have no additional properties in the POF.

> $Name: bta_morgens_dock_s2
> $Type: docking-stage-2
> +Triggered By: 2
> $Segment Parallel:
> 	$Rotation:
> 		+Angle: 0,0,90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_L-a
> 	$Rotation:
> 		+Angle: 0,0,-90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_R-a
> +End Segment
> 
> $Name: bta_morgens_docked
> $Type: docked
> +Triggered By: 2
> $Segment Parallel:
> 	$Rotation:
> 		+Angle: 0,0,-90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_L-a
> 	$Rotation:
> 		+Angle: 0,0,90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_R-a
> +End Segment

[fs2_open (5).log](https://github.com/scp-fs2open/fs2open.github.com/files/7966423/fs2_open.5.log)

### PR DESCRIPTION
**Pull request by BMagnu**
With the previous animation overhaul, some problems with the collision code came to light.
This PR aims to fix most of the more problematic ones, including:

- Fixes Global -> Local coordinate transformation for nested submodels (prerequisite for latter points)
- Fixes Submodel collisions for nested submodels more than two layers deep
- Fixes Submodel collisions for nested submodels that have moving ancestors
- Fixes Collision physics calculation for submodels with triggered animations (fixes #3985)
- Laid groundwork to follow up to improve the collision physics calculation to more accurately represent submodels with moving ancestors in a future PR

### CODE REVIEW

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Nicely done!  Just a few comments

File: code/object/collideshipship.cpp [hunk 1]
```diff
@@ -266,7 +266,8 @@ int ship_ship_check_collision(collision_info_struct *ship_ship_hit_info)
 			}
 
 			// reset flags to check MC_CHECK_MODEL | MC_CHECK_SPHERELINE and maybe MC_CHECK_INVISIBLE_FACES and MC_SUBMODEL_INSTANCE
```
Comment (Goober5000) [inline code/object/collideshipship.cpp:268]: also the question about the mc flags

**Review by Goober5000 — APPROVED** [review]
