### PR TITLE
Fix 3980

### LINKED ISSUE #3980: Pilot conversion notification not displayed after the first pilot
Expected: Pilot conversion infobox should be displayed whenever a pilot file is upgraded to v5, but only once for each pilot
Actual: The infobox is only displayed once, ever

Steps to reproduce:
1) Create a pilot on a 21.4 build
2) Launch 21.5.  The infobox is displayed
3) Create another pilot on a 21.4 build
4) Launch 21.5.  The infobox is not displayed, even after selecting and launching the newest pilot

### PR DESCRIPTION
**Pull request by z64555**
Should fix #3980 

Alright, This PR adds a number of QoL features and logic flow of selecting a pilot from the player menu, which is the first screen that player see right after the intro movie.

* When players try to a accept a selected pilot, the pilot is checked to see if it is valid. They will be notified with a popup to alert them that the selected file is an older version and prompt them if they want to continue and convert the pilot.
  * Since we can now intercept players before committing to the pilot, we can safely convert the pilot to the version FSO wants to work with.  This is done after the players have committed to using the pilot.  This is to ensure expected behavior of "convert pilot on commit."
* When players enter the mainhall and the verification process detected the pilot was a pre Controls5 save, a popup will be displayed to tell them to check their control bindings

- [x] Investigate option to clone pilot from the version mismatch popup
- [x] XSTR() support in popups.

Adds the following XSTR's:
1662: "Unable to open pilot file %s!"
1663: "Warning!\n\nSelected pilot was created with a different version of Freespace.\n\n"...
1664: "Notice!\n\nThe currently selected pilot was from a version older than FSO 22.0.\n\n"...

image

image

### CODE REVIEW

File: code/menuui/playermenu.cpp [hunk 1]
```diff
@@ -574,17 +574,39 @@ void player_select_button_pressed(int n)
...
+				"to the currently active language.\n\n"
+				"Please select a different pilot or change the language", 1637));
+			goto player_select_nocommit;
+		}
+		
+		if (Player->flags & PLAYER_FLAGS_PLR_VER_LOWER) {
+			// warning: Selected player is older than the expected version
+			int sel = popup(PF_BODY_RED, 2, POPUP_YES, POPUP_NO, "Selected pilot was created with an older version of Freespace.\n"
+				"Should you continue with this pilot, it will be updated to version %i.\n"
+				"This update is irreversiable and may make the pilot incompatible with older versions.\n"
```
Comment (Goober5000) [inline code/menuui/playermenu.cpp:595]: "irreversible" is misspelled

**Comment by z64555** [comment]
Barracks is still giving me trouble, not showing the popup when a pre-controls5 pilot is selected/cloned from the barracks, but I suppose this is good enough to get into the RC phase once CI is appeased.

**Comment by z64555** [comment]
Ugh, CI failed on testing the binary == json reads.  I have no idea which change might have caused this at this time. Will resume tomorrow

**Comment by Goober5000** [comment]
I will try to review this on Saturday.

File: code/menuui/playermenu.cpp [hunk 2]
```diff
@@ -1410,6 +1458,26 @@ void player_tips_popup()
...
+	if (Player->save_flags & PLAYER_FLAGS_PLR_VER_CONTROLS) {
+		// Special case. Since the Controls5 PR is significantly different from retail, users must be informed
+		// of changes regarding their bindings
+
+		Player->save_flags &= ~PLAYER_FLAGS_PLR_VER_CONTROLS;	// Clear the flag, since we're notifying the user right now
+
+		int sel = popup(PF_NO_SPECIAL_BUTTONS | PF_TITLE_BIG | PF_TITLE_GREEN, 2, POPUP_OK, XSTR("Don't show me this again", 1443),
+						XSTR("Notice!\n\n"
+						"The currently selected pilot was from a version older than FSO 22.0.\n\n"
+						"It is strongly recommended that you verify your control bindings within the Options -> Control Config menu.\n", 1664));
```
Comment (Goober5000) [inline code/menuui/playermenu.cpp:1471]: I don't think you need a newline at the end.

File: code/menuui/playermenu.cpp [hunk 3]
```diff
@@ -204,26 +204,78 @@ void player_select_eval_very_first_pilot();
...
+
+	// verify pilot language = current FSO language
 	lcl_get_language_name(current_lang);
+	if (strcmp(current_lang, pilot_lang) != 0) {
+		// error: Different language
+		if (!no_popup) {
+			popup(PF_USE_AFFIRMATIVE_ICON, 1, POPUP_OK, XSTR(
+				"Selected pilot was created with a different language\n"
+				"to the currently active language.\n\n"
+				"Please select a different pilot or change the language", 1637));
```
Comment (Goober5000) [inline code/menuui/playermenu.cpp:232]: Need a period at the end of the string

File: code/playerman/player.h [hunk 4]
```diff
@@ -52,6 +52,9 @@
 #define PLAYER_FLAGS_KILLED_SELF_UNKNOWN			(1<<16)		// player died by his own hand
 #define PLAYER_FLAGS_KILLED_SELF_MISSILES			(1<<17)		// player died by his own missile
 #define PLAYER_FLAGS_KILLED_SELF_SHOCKWAVE		(1<<18)		// player died by his own shockwave
+#define PLAYER_FLAGS_PLR_VER_CONTROLS		(1<<19)		// loaded PLR file's plr_ver is a pre-controls5 version
+#define PLAYER_FLAGS_PLR_VER_LOWER			(1<<20)		// loaded PLR file's plr_ver is lower than PLR_VERSION
+#define PLAYER_FLAGS_PLR_VER_HIGHER			(1<<21)		// loaded PLR file's plr_ver is higher than PLR_VERSION
```
Comment (Goober5000) [inline code/playerman/player.h:57]: I'd rename these.  `PLAYER_FLAGS_PLR_VER_CONTROLS` should be `PLAYER_FLAGS_PLR_VER_OLD_CONTROLS` or maybe `PLAYER_FLAGS_PLR_VER_PRE_CONTROLS5`.  Something a little more descriptive.  The other two are better but I would prefer `PLAYER_FLAGS_PLR_VER_IS_LOWER` and `PLAYER_FLAGS_PLR_VER_IS_HIGHER`

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Some comments

File: code/menuui/playermenu.cpp [hunk 5]
```diff
@@ -154,8 +154,8 @@ int Player_select_num_pilots;						// # of pilots on the list
 int Player_select_list_start;						// index of first list item to start displaying in the box
 int Player_select_pilot;							// index into the Pilot array of which is selected as the active pilot
 int Player_select_input_mode;						// 0 if the player _isn't_ typing a callsign, 1 if he is
-char Pilots_arr[MAX_PILOTS][MAX_FILENAME_LEN];
-char *Pilots[MAX_PILOTS];
+char Pilots_arr[MAX_PILOTS][MAX_FILENAME_LEN];		// Filename of associated Pilot. Same idx as Pilots[]
+char *Pilots[MAX_PILOTS];							// Pilot callsigns
```
Comment (Goober5000) [inline code/menuui/playermenu.cpp:158]: Also can this be made into a `const char *`?

Comment (z64555) [reply code/menuui/playermenu.cpp:158]: Which one? `Pilots_arr[][]` or `Pilots[]`?

Comment (Goober5000) [reply code/menuui/playermenu.cpp:158]: `Pilots[]`

Comment (z64555) [reply code/menuui/playermenu.cpp:158]: No, `Pilots[]` can not be `const char *` because the menu code modifies the array to do sorting and adding new pilots.  It may be possible to do this change but it would require more extensive changes elsewhere.

File: code/playerman/player.h [hunk 6]
```diff
@@ -52,9 +52,9 @@
 #define PLAYER_FLAGS_KILLED_SELF_UNKNOWN			(1<<16)		// player died by his own hand
 #define PLAYER_FLAGS_KILLED_SELF_MISSILES			(1<<17)		// player died by his own missile
 #define PLAYER_FLAGS_KILLED_SELF_SHOCKWAVE		(1<<18)		// player died by his own shockwave
-#define PLAYER_FLAGS_PLR_VER_CONTROLS		(1<<19)		// loaded PLR file's plr_ver is a pre-controls5 version
-#define PLAYER_FLAGS_PLR_VER_LOWER			(1<<20)		// loaded PLR file's plr_ver is lower than PLR_VERSION
-#define PLAYER_FLAGS_PLR_VER_HIGHER			(1<<21)		// loaded PLR file's plr_ver is higher than PLR_VERSION
+#define PLAYER_FLAGS_PLR_VER_PRE_CONTROLS		(1<<19)		// loaded PLR file's plr_ver is a pre-controls5 version
```
Comment (Goober5000) [inline code/playerman/player.h:55]: `PRE_CONTROLS5`, not `PRE_CONTROLS`, unless this was intentional

**Review by Goober5000 — APPROVED** [review]
