### PR TITLE
Fixes Team Colors not working with `show-ship`

### LINKED ISSUE #4435: Team color does not show up on `show-ship` from first person view
If the player is in first-person view with a ship that uses `show-ship` flag, then team colors do not appear. If the player switches to third-person then the team colors are properly visible.

### PR DESCRIPTION
**Pull request by wookieejedi**
Updates the `show-ship` function to account for team colors. Also, cleans up the function a bit. Tested and works as expected. Fixes #4435

### CODE REVIEW

File: code/ship/ship.cpp [hunk 1]
```diff
@@ -7419,10 +7419,20 @@ void ship_render_show_ship_cockpit(object *objp)
 	model_render_params render_info;
 
 	render_info.set_object_number(OBJ_INDEX(objp));
-	render_info.set_replacement_textures(Ships[objp->instance].ship_replacement_textures);
+
+	// update any replacement and/or team color textures (wookieejedi), then render
+	ship* shipp = &Ships[objp->instance];
+	ship_info* sip = &Ship_info[Ships[objp->instance].ship_info_index];
+
+	render_info.set_replacement_textures(shipp->ship_replacement_textures);
```
Comment (JohnAFernandez) [inline code/ship/ship.cpp:7427]: There's no need to check that the textures are valid before calling? Does `set_replacement_textures` already check?

Comment (wookieejedi) [reply code/ship/ship.cpp:7427]: Good question. That function does not have that `is_team_color_set` check within it. As such, all other calls of `render_info.set_replacement_textures` had that same `if` check.

**Review by JohnAFernandez — APPROVED** [review]
