### PR TITLE
Fix warning of unbound keys for newer controls

### LINKED ISSUE #7172: New control strings are not displayed correctly in warning about unbound keys
Under some circumstances, FSO will warn the player if a key is unbound if that they need to press to complete a training event. This logic though only works for keys with XSTRs from 507-619. Any control that was added with a different XSTR will not be picked up correctly, and thus the message displayed to the player will be incorrect, confusing, and not helpful. 

Here is an example, where the incorrect XSTR look resulted in a very confusing message:

Image

To fix this `missiontraining.cpp` around line 757 needs to account for the newer controls as well. I'm going to work on a PR for this.

### PR DESCRIPTION
**Pull request by wookieejedi**
Under some circumstances, FSO will warn the player if a key is unbound if that they need to press to complete a training event. This logic though only works for keys with XSTRs from 507-619. Any control that was added with a different XSTR will not be picked up correctly, and thus the message displayed to the player will be incorrect, confusing, and not helpful.

To fix this `missiontraining.cpp` around line 757 needs to account for the newer controls as well.

This PR adds those needed checks, and this fixes the issue. This fix is especially needed for mods that use training missions with newer controls such as FotG. Note, we do ship with a full default controls table with all the needed keys bound, but we have found players will be players and simply change all their controls before even starting the training missions. Thus they unbind key training controls, and with this bug they are unable to correct their controls. With this fix they are properly able to update their controls as needed to complete the training missions.

Fixes #7172.

### CODE REVIEW

**Review by Goober5000 — APPROVED** [review]

File: code/mission/missiontraining.cpp [hunk 1]
```diff
@@ -754,10 +754,17 @@ SCP_string message_translate_tokens(const char *text)
 					if (!stricmp(ptr, NOX("none")) && (Training_bind_warning != Missiontime)) {
 						// check if a warning message should be displayed if the key is unbound
 						if ( (The_mission.game_type & MISSION_TYPE_TRAINING) || (Always_warn_player_about_unbound_keys && (The_mission.game_type & MISSION_TYPE_SINGLE)) ) {
+							int index_to_use;
```
Comment (Goober5000) [inline code/mission/missiontraining.cpp]: Trivial, but could you rename `index_to_use` to something like `xstr_index`?

Comment (wookieejedi) [reply code/mission/missiontraining.cpp]: Good idea, just updated!
