### PR TITLE
'detonate on expiration' weapon flag

### LINKED ISSUE #5521: Detonate-on-death flag for weapons
Weapons spawning their hit effects when they run out of life rather than just disappearing is pretty. This can be done using $Detonation Range.

However, setting the $Detonation Range to a value equal to the weapon's maximum range (such that it detonates during the same frame in which it dies) will cause the effect to only spawn sometimes, probably because the order in which weapon-killing and effect-spawning occur is nondeterministic. In order to get reliable behavior, one must increase the lifetime of the weapon slightly.

In complex table-stack situations, such as are common with the MediaVPs, this can result in unexpected overrides and bugs.

The best solution to this problem is a simple flag one can add to a weapon which causes it to always detonate when its life runs out.

### PR DESCRIPTION
**Pull request by Goober5000**
For mods which want primary weapons to 'detonate', setting the detonation range is not reliable because, due to rounding imprecision, either the range (which detonates) or the lifetime (which does not) may happen first.  So this adds a flag to always detonate a weapon when its lifetime expires.  Secondary weapons have this flag by default, but primary weapons can add this flag in the $Flags list.  Additionally, if the detonation range and the predicted range due to lifetime are equal, the flag is added automatically.

Resolves #5521.

### CODE REVIEW

**Review by wookieejedi — APPROVED** [review]

File: code/weapon/weapons.cpp [hunk 1]
```diff
@@ -5718,27 +5734,28 @@ void weapon_process_post(object * obj, float frame_time)
...
-			if (wip->is_homing()) {
-				Homing_misses++;
-			}
 		} else {
             obj->flags.set(Object::Object_Flags::Should_be_dead);
 		}
+
+		if (wip->is_homing()) {
+			Homing_misses++;
+		}
```
Comment (JohnAFernandez) [inline code/weapon/weapons.cpp:5758]: I'm not 100% sure this is intentional.  Previously this was triggered if `( wip->subtype & WP_MISSILE ) {` .  So this should either be moved back to somewhere it has the equivalent behavior, or changed to `if ( wip->subtype & WP_MISSILE  && wip->is_homing) {`

**Review by JohnAFernandez — CHANGES_REQUESTED** [review]

File: code/weapon/weapons.cpp (hunk 1 above)
Comment (Goober5000) [reply code/weapon/weapons.cpp:5758]: It's intentional, since primary weapons can home now.  But upon taking a closer look at that variable, its only use is to provide information for an `nprintf` that is now commented out.  So I'll remove it.

Comment (JohnAFernandez) [reply code/weapon/weapons.cpp]: All right.  Yeah, any coder that needs that information to balance AI can recreate the statements pretty easily.

**Review by JohnAFernandez — APPROVED** [review]
