### PR TITLE
Fix standalone web UI crash when polling player data before ship selection

### LINKED ISSUE #7366: Standalone web UI crashes when polling player data before ship selection
## Summary

The standalone server's web API crashes with an out-of-bounds vector access in `playerGet()` when the web UI polls for player data while a connected player has not yet been assigned a ship (e.g., during mission loading).

## Steps to Reproduce

1. Start a standalone server with the web UI open
2. Connect a client and select a mission
3. Start the mission load process
4. If the web UI polls during loading, the standalone crashes

This is easier to trigger with mods that have longer load times (e.g., FotG), since the window where `ship_class == -1` is wider. With retail data, the load is fast enough that the poll is unlikely to land during the window, though it's still possible. On a FastDebug build without
assertions, the out-of-bounds read doesn't crash but produces garbled data, causing a DataTables JS error on the web frontend:

DataTables warning (table id = 'clientsTable'): Requested unknown parameter 'ship' from the data source for row 0

## Root Cause

In `stand_gui-unix.cpp:460`, `playerGet()` indexes `Ship_info` with `p.p_info.ship_class` without bounds checking:

```cpp
json_object_set(obj, "ship", json_string(Ship_info[p.p_info.ship_class].name));
```

Before a player selects a ship, ship_class is -1. As an unsigned size_type, this becomes 18446744073709551615, triggering _GLIBCXX_ASSERTIONS on debug builds or reading garbage memory on release builds.

The Windows standalone GUI (stand_gui.cpp:1070) already has the correct bounds check:

```cpp
if (p->p_info.ship_class >= 0 && p->p_info.ship_class < static_cast<int>(Ship_info.size())) {
    SetWindowText(Player_ship_type, Ship_info[p->p_info.ship_class].name);
```

The Unix/web version was missing the equivalent guard.

**Fix**

Add the same bounds check from the Windows GUI to the Unix web API's playerGet(), returning an empty string for the ship name when ship_class is out of range.

**Stack Trace**

```
#0  __pthread_kill_implementation () at pthread_kill.c:44
#1  __pthread_kill_internal () at pthread_kill.c:89
#2  __GI_raise () at ../sysdeps/posix/raise.c:26
#3  __GI_abort () at abort.c:77
#4  std::__glibcxx_assert_fail () at assert_fail.cc:41
#5  std::vector<ship_info>::operator[] (__n=18446744073709551615) at stl_vector.h:1263
#6  playerGet () at stand_gui-unix.cpp:460
#7  webserverApiRequest () at stand_gui-unix.cpp:656
#8  webserverCallback () at stand_gui-unix.cpp:682
#9-#12 [mongoose web server worker thread]
```

### PR DESCRIPTION
**Pull request by chief1983**
playerGet() indexed Ship_info with ship_class without bounds checking. Before ship selection, ship_class is -1, which as an unsigned index causes an out-of-bounds access. Add the same bounds check that the Windows standalone GUI already has.

Fixes #7366

### CODE REVIEW

**Comment by wookieejedi** [comment]
Reckon this is another one that would be great to have @notimaginative's take on.

File: code/network/stand_gui-unix.cpp [hunk 1]
```diff
@@ -457,7 +457,11 @@ json_t* playerGet(ResourceContext * /*context*/) {
         json_object_set(obj, "host", (MULTI_HOST(p)) ? json_true() : json_false());
         json_object_set(obj, "observer", (MULTI_OBSERVER(p)) ? json_true() : json_false());
         json_object_set(obj, "callsign", json_string(p.m_player->callsign));
-        json_object_set(obj, "ship", json_string(Ship_info[p.p_info.ship_class].name));
+        if (p.p_info.ship_class >= 0 && p.p_info.ship_class < static_cast<int>(Ship_info.size())) {
```
Comment (notimaginative) [inline code/network/stand_gui-unix.cpp]: I believe using `ship_info_size()` is the preferred way to do the upper bounds check. Otherwise this looks good to me.

**Review by notimaginative — CHANGES_REQUESTED** [review]

File: code/network/stand_gui-unix.cpp (hunk 1 above)
Comment (chief1983) [reply code/network/stand_gui-unix.cpp]: It had actually copied the pattern from the Windows stand_gui.cpp file, so guessing we could update that one as well?
```
1070 -  if (p->p_info.ship_class >= 0 && p->p_info.ship_class < static_cast<int>(Ship_info.size())) {
1070 +  if (p->p_info.ship_class >= 0 && p->p_info.ship_class < ship_info_size()) {
```
Went ahead and pushed a version with that change made.

**Review by notimaginative — APPROVED** [review]
