### PR TITLE
fix ship:warpIn() behavior for docked ships

### LINKED ISSUE #6445: In-mission docking breaks the `warpIn()` scripting function
Bit of a niche case here... If a ship is not initially docked, or is initially docked but isn't the dock leader, and becomes docked during gameplay, calling the `warpIn()` scripting function on that ship will do nothing until it becomes undocked. This is due to a combination of two factors: `warpIn()` calls `shipfx_warpin_start(object*)`, which short-circuits if it's called on a ship that's docked but not a `Dock_leader`; and the `Dock_leader` flag is only set at parse time, not as a result of docking during gameplay. Even if `Dock_leader` were updated dynamically, `warpIn()` would still mysteriously do nothing in some cases, so I feel like the right solution is to have `shipfx_warpin_start` skip that check when called by `warpIn()`.

Additionally, `shipfx_warpin_start` fails with an `Int3()` when called on a ship that's already arriving; it should just do nothing in this case.

### PR DESCRIPTION
**Pull request by Goober5000**
As described in #6445, the `warpIn()` script function did not work correctly for docked ships because the dock leader flag was not set.  So, set the flag, but make sure to set it only for the first ship for which `warpIn()` is called.  And make sure the flag is removed after the ship finishes arriving.

Also remove an `Int3()` in `shipfx_warpin_start()`.  (This Int3() was not actually in the original Volition source code release.)

Fixes #6445.

### CODE REVIEW

File: code/scripting/api/objs/ship.cpp [hunk 1]
```diff
@@ -2104,6 +2104,17 @@ ADE_FUNC(warpIn, l_Ship, NULL, "Warps ship in", "boolean", "True if successful,
 	if(!objh->isValid())
 		return ADE_RETURN_NIL;
 
+	if (object_is_docked(objh->objp()))
+	{
+		// Ships that are docked need a designated dock leader to bring the entire group in.  The dock leader is, de facto, the arriving ship;
+		// so by scripting a certain ship to warp in, the script author has designated it as the leader.  That being said, if the script
+		// calls warpIn() multiple times on the same docked group, only set the flag on the first ship.
+		dock_function_info dfi;
+		dock_evaluate_all_docked_objects(objh->objp(), &dfi, dock_find_dock_leader_helper);
```
Comment (naomimyselfandi) [inline code/scripting/api/objs/ship.cpp:2113]: This still leaves a corner case where `warpIn()` will mysteriously fail to do anything. Suppose we're in a pirate campaign, and in the first phase of the mission, the player is tasked with disabling a freighter and escorting a capture transport; in the second phase, the capture transport does a series of in-mission jumps to avoid pursuit, like BtA's "Shell Game". That will fail for no obvious reason if the freighter is initially carrying cargo. (I know that's pretty niche, but I _think_ it came up in an early draft of a BtA mission. I say "I think" because I was already souring on the design of that mission, so I didn't dig into it too closely; I'm going off a vague memory here.)

Removing the `Dock_leader` flag when a ship finishes arriving would avoid that issue (as well as a preexisting issue where two ships that are both dock leaders become (directly or indirectly) docked before `warpIn()` is called).

If that's not practical, we could just make the ship `warpIn()` is called on the dock leader (removing the flag from anything it's docked to), and document that `warpIn()` shouldn't be called on multiple ships in the same dock group.

**Review by naomimyselfandi — CHANGES_REQUESTED** [review]

File: code/scripting/api/objs/ship.cpp (hunk 1 above)
Comment (Goober5000) [reply code/scripting/api/objs/ship.cpp:2113]: Niche cases are important too!  They were certainly the bane of my debugging efforts on the red-alert system, the sounds.tbl system, and plenty of other situations.

Removing the `Dock_leader` flag after arrival is the perfect solution, and is in fact something I thought was part of the code already.  I've amended the PR with the change.

**Review by naomimyselfandi — APPROVED** [review]
Thanks for handling the corner case. Lgtm!

**Review by wookieejedi — APPROVED** [review]
Thanks for approving Naomi!
